<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $questions = [
            /***********************************************/
            [ 'question' => 'Overall, are you satisfied with the outputs and results of "name"?', 'category_id' => 31, 'type' => 'customer' ],
            [ 'question' => 'Did "name" meet the targets according to your expectations?', 'category_id' => 31, 'type' => 'customer' ],
            [ 'question' => 'Did "name" meet the minimal quality levels?', 'category_id' => 32, 'type' => 'customer' ],
            [ 'question' => 'Did "name" meet the predetermined deadline(s)?', 'category_id' => 42, 'type' => 'customer' ],
            [ 'question' => 'To your feeling, is "name" working efficiently?', 'category_id' => 43, 'type' => 'customer' ],
            [ 'question' => 'Are the (technical) skills of "name" at par with what is required for his role?', 'category_id' => 34, 'type' => 'customer' ],
            [ 'question' => 'Is "name" able to think on a strategical level?', 'category_id' => 35, 'type' => 'customer' ],
            [ 'question' => 'Does "name" come up with ideas and suggestions?', 'category_id' => 35, 'type' => 'customer' ],
            [ 'question' => 'Has "name" grown towards the objectives set last year?', 'category_id' => 36, 'type' => 'customer' ],
            [ 'question' => 'Are the communication skills of "name" at par with what is required for his role?', 'category_id' => 44, 'type' => 'customer' ],
            [ 'question' => 'Is there a clear email and chat etiquette that needs to be followed?', 'category_id' => 45, 'type' => 'customer' ],
            [ 'question' => 'Does "name" follow the email and chat etiquette?', 'category_id' => 45, 'type' => 'customer' ],
            [ 'question' => 'Does "name" use an adequate speaking style?', 'category_id' => 46, 'type' => 'customer' ],
            [ 'question' => 'Does "name" know who to contact for which problem?', 'category_id' => 47, 'type' => 'customer' ],
            [ 'question' => 'Does "name" know what channel to use for each message?', 'category_id' => 47, 'type' => 'customer' ],
            [ 'question' => 'Am I documenting my work according to the expectations of the customer?', 'category_id' => 48, 'type' => 'customer' ],
            [ 'question' => 'How much autonomy is required to fulfill the role of "name"?', 'category_id' => 15, 'type' => 'customer' ],
            [ 'question' => 'Can "name" make decisions in his own area of work?', 'category_id' => 1, 'type' => 'customer' ],
            [ 'question' => 'Does "name" take ownership within his role?', 'category_id' => 1, 'type' => 'customer' ],
            [ 'question' => 'How much autonomy does "name" get to fulfill his role?', 'category_id' => 1, 'type' => 'customer' ],
            [ 'question' => 'How able is "name" to handle autonomy and independence?', 'category_id' => 1, 'type' => 'customer' ],
            [ 'question' => 'Do I go the extra mile in order to achieve the wanted result?', 'category_id' => 16, 'type' => 'customer' ],
            [ 'question' => 'Do I feel that "name" is going the extra mile to get the wanted result?', 'category_id' => 1, 'type' => 'customer' ],
            [ 'question' => 'Are the agreed commitments being respected by "name"?', 'category_id' => 17, 'type' => 'customer' ],
            [ 'question' => 'Does "name" know what the impact is of the role he fulfills and where his role fits in the bigger picture of the business?', 'category_id' => 18, 'type' => 'customer' ],
            [ 'question' => 'Does "name" take time to think about next steps within his role and proactivity act on it?', 'category_id' => 38, 'type' => 'customer' ],
            [ 'question' => 'Do I know what projects are planned in the short term and which "name" will take on?', 'category_id' => 39, 'type' => 'customer' ],
            [ 'question' => 'Does "name" get invited to participate in team meetings, within the frame of his role?', 'category_id' => 19, 'type' => 'customer' ],
            [ 'question' => 'Does "name" get first line feedback?', 'category_id' => 20, 'type' => 'customer' ],
            [ 'question' => 'Is there a clear future perspective for the team in the organization?', 'category_id' => 40, 'type' => 'customer' ],
            [ 'question' => 'Is it clear what projects are planned in long term for "name"?', 'category_id' => 41, 'type' => 'customer' ],
            [ 'question' => 'How likely is it that the work environment will change and the role of "name" will not be relevant anymore?', 'category_id' => 1, 'type' => 'customer' ],
            [ 'question' => 'Does "name" get enough guidance, supervision or support from you?', 'category_id' => 7, 'type' => 'customer' ],
            [ 'question' => 'How often did "name" provide you with helpful information or advice?', 'category_id' => 2, 'type' => 'customer' ],
            [ 'question' => 'Does "name" respond with sympathetic understanding whenever you have an issue or problem?', 'category_id' => 2, 'type' => 'customer' ],
            [ 'question' => 'How often did "name" provide you with clear and helpful feedback?', 'category_id' => 2, 'type' => 'customer' ],
            [ 'question' => 'Does "name" help me find a solution whenever I have a question or an issue?', 'category_id' => 2, 'type' => 'customer' ],
            [ 'question' => 'Overall, is there a positive relationship with "name"?', 'category_id' => 8, 'type' => 'customer' ],
            [ 'question' => 'What is shared? Background, interest, experience, beliefs, vision...', 'category_id' => 2, 'type' => 'customer' ],
            [ 'question' => 'How smoothly is the contact with "name"?', 'category_id' => 2, 'type' => 'customer' ],
            [ 'question' => 'Is there a shared vision of the future?', 'category_id' => 22, 'type' => 'customer' ],
            [ 'question' => 'How certain do you feel "name" will stay part of the team for the next year?', 'category_id' => 2, 'type' => 'customer' ],
            [ 'question' => 'How likely is it that I will pursue other things and will not be part of the team next year?', 'category_id' => 2, 'type' => 'customer' ],
            [ 'question' => 'Do I feel that "name" takes time to dive into my work and provide me with relevant feedback ', 'category_id' => 23, 'type' => 'customer' ],
            [ 'question' => 'When I do a good job, I receive the recognition that I should receive?', 'category_id' => 24, 'type' => 'customer' ],
            [ 'question' => 'Do I feel heard?', 'category_id' => 3, 'type' => 'customer' ],
            [ 'question' => 'Are my unique skills and talents valued and utilised?', 'category_id' => 3, 'type' => 'customer' ],
            [ 'question' => 'Do I get invited to team celebrations?', 'category_id' => 3, 'type' => 'customer' ],
            [ 'question' => 'Do I feel challenged in my work environment?', 'category_id' => 26, 'type' => 'customer' ],
            [ 'question' => 'I feel a sense of pride in doing my work?', 'category_id' => 27, 'type' => 'customer' ],
            [ 'question' => 'I like doing the things I do at work?', 'category_id' => 28, 'type' => 'customer' ],
            [ 'question' => 'Is it okay to ask questions?', 'category_id' => 29, 'type' => 'customer' ],
            [ 'question' => 'Is it okay to ask help?', 'category_id' => 29, 'type' => 'customer' ],
            [ 'question' => 'Is it okay to experiment or take risks?', 'category_id' => 29, 'type' => 'customer' ],
            [ 'question' => 'Is it okay to make mistakes?', 'category_id' => 29, 'type' => 'customer' ],
            [ 'question' => 'If I make a mistake, it is never held against me?', 'category_id' => 29, 'type' => 'customer' ],
            [ 'question' => 'Is it okay to show vulnerability or admit a knowlegde gap?', 'category_id' => 29, 'type' => 'customer' ],
            [ 'question' => 'Do I feel able to bring up problems and tough issues?', 'category_id' => 29, 'type' => 'customer' ],
            [ 'question' => 'Do I have a good platform or am I able to ask questions and discuss problems when needed?', 'category_id' => 29, 'type' => 'customer' ],
            [ 'question' => 'Is it okay to contribute ideas?', 'category_id' => 30, 'type' => 'customer' ],
            [ 'question' => 'Do I have the ability or platform to share ideas?', 'category_id' => 30, 'type' => 'customer' ],
            [ 'question' => 'Do I feel comfortable taking initiative?', 'category_id' => 30, 'type' => 'customer' ],
            [ 'question' => 'Do I feel comfortable giving feedback?', 'category_id' => 30, 'type' => 'customer' ],
            [ 'question' => 'Am I able to deal with feedback?', 'category_id' => 30, 'type' => 'customer' ],
            [ 'question' => 'Do I take feedback personal?', 'category_id' => 30, 'type' => 'customer' ],
            [ 'question' => 'Is it okay to speak up and point out mistakes?', 'category_id' => 30, 'type' => 'customer' ],
            [ 'question' => 'Is it okay to open dialogue or discussion?', 'category_id' => 30, 'type' => 'customer' ],
            [ 'question' => 'Is my role cristal clear to me?', 'category_id' => 31, 'type' => 'developer' ],
            [ 'question' => 'Overall, am I satisfied with the output I deliver?', 'category_id' => 31, 'type' => 'developer' ],
            [ 'question' => 'Do I know what the quality requirements are for the role I fulfill?', 'category_id' => 32, 'type' => 'developer' ],
            [ 'question' => 'Was I able to meet the minimal quality levels according to expectations?', 'category_id' => 33, 'type' => 'developer' ],
            [ 'question' => 'Do I know which work speed is required from me or when I have to meet deadlines?', 'category_id' => 33, 'type' => 'developer' ],
            [ 'question' => 'Was I able to meet the deadlines or to deliver at the expected speed?', 'category_id' => 34, 'type' => 'developer' ],
            [ 'question' => 'Are the agreed commitments respected by "name"?', 'category_id' => 35, 'type' => 'developer' ],
            [ 'question' => 'Do I know what projects are planned in short term and which I will take on?', 'category_id' => 35, 'type' => 'developer' ],
            [ 'question' => 'Do I feel like going the extra mile in order to achieve result?', 'category_id' => 36, 'type' => 'developer' ],
            [ 'question' => 'Do I feel that "name" are going the extra mile in order to achieve the wanted result?', 'category_id' => 44, 'type' => 'developer' ],
            [ 'question' => 'Are my technical skills at par with what is required, enough to fulfill my role?', 'category_id' => 1, 'type' => 'developer' ],
            [ 'question' => 'Do I feel I have grown towards the objectives set last year?', 'category_id' => 1, 'type' => 'developer' ],
            [ 'question' => 'Does it cost me effort to fulfill my role?', 'category_id' => 1, 'type' => 'developer' ],
            [ 'question' => 'Am I able to think on a strategical level with the business?', 'category_id' => 1, 'type' => 'developer' ],
            [ 'question' => 'Am I able to bring ideas and suggestions?', 'category_id' => 1, 'type' => 'developer' ],
            [ 'question' => 'Are my communication skills at par with what is required for my role?', 'category_id' => 1, 'type' => 'developer' ],
            [ 'question' => 'Do I know who to contact for which problem?', 'category_id' => 17, 'type' => 'developer' ],
            [ 'question' => 'Is there a clear email and chat etiquette that needs to be followed?', 'category_id' => 18, 'type' => 'developer' ],
            [ 'question' => 'Does "name" follow the email and chat etiquette?', 'category_id' => 38, 'type' => 'developer' ],
            [ 'question' => 'Does "name" use an adequate speaking style?', 'category_id' => 39, 'type' => 'developer' ],
            [ 'question' => 'Do I get enough autonomy to fulfill my role?', 'category_id' => 19, 'type' => 'developer' ],
            [ 'question' => 'Do I experience intense micromanagement from?', 'category_id' => 20, 'type' => 'developer' ],
            [ 'question' => 'Can I make my own decisions in my area of work?', 'category_id' => 40, 'type' => 'developer' ],
            [ 'question' => 'Do I have a say in my own work speed?', 'category_id' => 41, 'type' => 'developer' ],
            [ 'question' => 'Do I take ownership within my role?', 'category_id' => 1, 'type' => 'developer' ],
            [ 'question' => 'Does "name" get enough guidance, supervision or support from you?', 'category_id' => 7, 'type' => 'developer' ],
            [ 'question' => 'How often did "name" provide you with helpful information or advice?', 'category_id' => 2, 'type' => 'developer' ],
            [ 'question' => 'Does "name" respond with sympathetic understanding whenever you have an issue or problem?', 'category_id' => 2, 'type' => 'developer' ],
            [ 'question' => 'How often did "name" provide you with clear and helpful feedback?', 'category_id' => 2, 'type' => 'developer' ],
            [ 'question' => 'Does "name" help you find a solution whenever I have a question or an issue?', 'category_id' => 2, 'type' => 'developer' ],
            [ 'question' => 'Overall, is there a positive relationship with "name"?', 'category_id' => 8, 'type' => 'developer' ],
            [ 'question' => 'What is shared? Background, interest, experience, beliefs, vision...', 'category_id' => 2, 'type' => 'developer' ],
            [ 'question' => 'How smoothly is the contact with "name"?', 'category_id' => 2, 'type' => 'developer' ],
            [ 'question' => 'Is there a shared vision of the future?', 'category_id' => 22, 'type' => 'developer' ],
            [ 'question' => 'How certain do you feel "name" will stay part of the team for the next year?', 'category_id' => 2, 'type' => 'developer' ],
            [ 'question' => 'How likely is it that I will pursue other things and will not be part of the team next year?', 'category_id' => 2, 'type' => 'developer' ],
        ];

        DB::table('questions')->insert($questions);
    }
}
